In [4]:
import numpy as np

## **Indexing and Slicing in NumPy**  
- NumPy arrays support flexible indexing and slicing for efficient data manipulation.  

### **Indexing**  
- Access elements using zero-based indexing.  
- Supports single element indexing, multi-dimensional indexing, and boolean indexing.  
- Fancy indexing allows selection using integer arrays.  

### **Slicing**  
- Uses the `[start:stop:step]` format to extract subarrays.  
- Can be applied to multiple dimensions.  
- Changes to slices affect the original array unless explicitly copied.  


In [17]:
arr = np.arange(50).reshape((5, 10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
arr2 = arr[:3] # slicing
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
arr2[:] = 100 # broadcasting

In [20]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [ ]:
arr
"""
Variables and Object Referencing in Python
- In Python, variables store references to objects in memory, not the actual data.  
- When one variable is assigned to another, they both reference the same object.  
- Modifying the new variable affects the original object, as both variables point to the same location in memory.  
- To avoid this, use the `.copy()` method to create a new, independent object.  
"""

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [23]:
arr2 = arr[:3].copy() # copying - change values without affecting original
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [ ]:
arr[1:4, 5:] # slicing with multiple dimensions (lines 1 to 4, columns 5 to end)
# arr[line, column] - line and column are both 0-indexed

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [27]:
bol = arr > 50 # boolean mask - returns a boolean array of the same shape as arr, where each element is True if the condition is met and False otherwise

In [28]:
arr[bol] # boolean indexing - returns the elements of arr that meet the condition specified by bol

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])