# **NumPy**
---
## **What is NumPy?**
- NumPy is a **linear algebra library for Python**.
- It serves as the **foundation** for many other data analysis libraries.
- **Highly optimized and fast**, as its core functions are implemented in **C**.

## **NumPy Arrays**
- One of the **most powerful tools** in NumPy.
- Can be visualized in two primary forms:
  - **Vectors**: **1D arrays**, containing a single row or column of elements.
  - **Matrices**: **2D arrays**, which can have multiple rows and columns (even if they contain only one row or column).

## **Why Use NumPy?**
- Efficient handling of **large datasets**.
- **Optimized performance** compared to Python lists.
- Essential for **scientific computing**, machine learning, and data analysis.

### **How to install and import?**

In [2]:
# !pip install numpy

In [3]:
import numpy as np # labeling as 'np' to simplify the code

In [4]:
my_list = [1, 2, 3]

In [5]:
my_list

[1, 2, 3]

## **Function - `np.array`**
- Creates an array object in NumPy
- Parameters: np.array(object, dtype, copy, order, subok, ndmin)
    - object: The input data, typically a list or list of lists
    - dtype (optional): The desired data type of the array elements
    - copy (optional): If True, the object is copied
    - order (optional): The desired memory layout order ('C' for row-major, 'F' for column-major)
    - subok (optional): If True, subclasses are passed through
    - ndmin (optional): Specifies the minimum number of dimensions

In [ ]:
np.array(my_list) # 1 dimensional array

array([1, 2, 3])

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix) # 2 dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Function - `np.arange`**
- Creates an array  with evenly spaced values
- Parameters: np.arange(start, stop, step)
  - start - starting value of the sequence
  - stop - end value (exclusive, doesn't appear in the sequence)
  - step - spacing between values

In [ ]:
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2) 

array([0, 2, 4, 6, 8])

## **Function - `np.zeros`**
- Creates an array filled with zeros
- Parameters: np.zeros(shape, dtype)
  - shape: The shape of the array (e.g., (3, 4) for a 3x4 array)
  - dtype (optional): The desired data type of the array elements

In [13]:
arr = np.zeros(3)

In [14]:
arr

array([0., 0., 0.])

In [15]:
arr = np.zeros((3, 4)) # 3 rows and 4 columns
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## **Function - `np.ones`**
- Creates an array filled with ones in NumPy
- Parameters: `np.ones(shape, dtype, order, like)`
    - `shape`: The shape of the output array (tuple or int)
    - `dtype` (optional): The desired data type of the array elements
    - `order` (optional): Memory layout order ('C' for row-major, 'F' for column-major)
    - `like` (optional): Reference array defining the output array’s attributes

In [16]:
np.ones((3, 3)) # 3 rows and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## **Function - `np.eye`**
- Creates a 2D identity matrix in NumPy
- Parameters: `np.eye(N, M, k, dtype, order, like)`
    - `N`: Number of rows in the output matrix
    - `M` (optional): Number of columns (default is `N`)
    - `k` (optional): Index of the diagonal (0 for main diagonal, positive for upper, negative for lower)
    - `dtype` (optional): The desired data type of the matrix elements
    - `order` (optional): Memory layout order ('C' for row-major, 'F' for column-major)
    - `like` (optional): Reference array defining the output array’s attributes


In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## **Function - `np.linspace`**  
- Generates evenly spaced values over a specified range in NumPy  
- Parameters: `np.linspace(start, stop, num, endpoint, retstep, dtype, axis)`  
    - `start`: The starting value of the sequence  
    - `stop`: The ending value of the sequence  
    - `num` (optional): Number of samples to generate (default is `50`)  
    - `endpoint` (optional): If `True`, includes `stop`; if `False`, excludes `stop`  
    - `retstep` (optional): If `True`, returns the step size along with the array  
    - `dtype` (optional): The desired data type of the output array  
    - `axis` (optional): The axis along which the values are stored (default is `0`)  


In [19]:
np.linspace(0, 10, 3) # 3 numbers between 0 and 10

array([ 0.,  5., 10.])

## **Function - `np.random`**  
- NumPy’s random module for generating random numbers  
- Common functions:  
    - `np.random.rand(d0, d1, ..., dn)`: Generates random values in `[0, 1)`  
    - `np.random.randn(d0, d1, ..., dn)`: Generates samples from a standard normal distribution  
    - `np.random.randint(low, high, size, dtype)`: Generates random integers in a given range  
    - `np.random.random(size)`: Generates random floats in `[0, 1)`  
    - `np.random.choice(a, size, replace, p)`: Randomly selects elements from an array  
    - `np.random.seed(seed)`: Sets the random seed for reproducibility  


In [20]:
np.random.rand(5) # 5 random numbers between 0 and 1

array([0.2551159 , 0.97718665, 0.97038453, 0.92767536, 0.38852482])

In [21]:
np.random.rand(5, 4) # 5 rows and 4 columns of random numbers between 0 and 1

array([[0.62410441, 0.60441859, 0.9966889 , 0.21071749],
       [0.81017363, 0.39068305, 0.51831093, 0.55615279],
       [0.46808878, 0.29376189, 0.69821935, 0.55784863],
       [0.53935953, 0.04799325, 0.4816203 , 0.22671075],
       [0.45822871, 0.42885918, 0.68708336, 0.75533128]])

In [22]:
np.random.rand(5, 4, 3) # 5 rows, 4 columns, and 3 depth of random numbers between 0 and 1

array([[[0.70022989, 0.83114165, 0.68998722],
        [0.89354908, 0.17626338, 0.17799395],
        [0.78806202, 0.22744074, 0.13046493],
        [0.03385916, 0.89371839, 0.46052176]],

       [[0.6920547 , 0.3928198 , 0.20406412],
        [0.62499875, 0.68881866, 0.79385383],
        [0.67680487, 0.01365964, 0.02456698],
        [0.78160214, 0.76089877, 0.8966341 ]],

       [[0.8806856 , 0.14630684, 0.76675896],
        [0.33762797, 0.55821201, 0.51687587],
        [0.43769361, 0.57514987, 0.30591697],
        [0.54866399, 0.08677931, 0.15702761]],

       [[0.74559318, 0.93590338, 0.09845336],
        [0.59502829, 0.91205196, 0.43134052],
        [0.92681728, 0.3862972 , 0.76342236],
        [0.01611257, 0.6090748 , 0.6381193 ]],

       [[0.71864629, 0.76738358, 0.7276156 ],
        [0.12653846, 0.75876004, 0.92601597],
        [0.98076167, 0.50736631, 0.08024637],
        [0.79687262, 0.46768092, 0.70836305]]])

In [24]:
np.random.randn(4) # 4 random numbers from a standard normal distribution

array([-0.6308434 , -0.67457749, -0.6520939 ,  1.19422544])

In [25]:
np.random.randint(0, 100, 10) # 10 random integers between 0 and 100

array([10, 13, 53, 10, 20, 20, 21, 64, 89, 72], dtype=int32)

## **Function - `np.round`**  
- Rounds elements of an array to the specified number of decimals in NumPy  
- Parameters: `np.round(a, decimals, out)`  
    - `a`: Input array to be rounded  
    - `decimals` (optional): Number of decimal places (default is `0`)  
    - `out` (optional): Output array to store the result (must have the same shape as `a`)  


In [26]:
np.round(np.random.rand(5) * 100, 0) # 5 random numbers between 0 and 100, rounded to the nearest integer

array([84.,  8., 47., 47., 96.])

## **Method - `.reshape`**  
- Reshapes an array without changing its data in NumPy  
- Parameters: `array.reshape(newshape, order)`  
    - `newshape`: The desired shape (tuple or int, must be compatible with the original size)  
    - `order` (optional): Memory layout order ('C' for row-major, 'F' for column-major, 'A' for automatic)  

In [27]:
arr = np.random.rand(25)

In [28]:
arr

array([0.81916972, 0.54019973, 0.33087804, 0.97111584, 0.20402698,
       0.7959643 , 0.14792776, 0.31136955, 0.05290453, 0.93175781,
       0.13917552, 0.90431162, 0.0326843 , 0.80983984, 0.85725812,
       0.24107486, 0.13168135, 0.33980873, 0.77779334, 0.73405625,
       0.70037844, 0.09228726, 0.03037639, 0.76563703, 0.01085554])

In [ ]:
arr = arr.reshape((5, 5)) # reshaping the array to 5 rows and 5 columns

array([[0.81916972, 0.54019973, 0.33087804, 0.97111584, 0.20402698],
       [0.7959643 , 0.14792776, 0.31136955, 0.05290453, 0.93175781],
       [0.13917552, 0.90431162, 0.0326843 , 0.80983984, 0.85725812],
       [0.24107486, 0.13168135, 0.33980873, 0.77779334, 0.73405625],
       [0.70037844, 0.09228726, 0.03037639, 0.76563703, 0.01085554]])

In [ ]:
arr